version: "3"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=sOm_e_dum8_p*ssw0|^d
      - DB_USER=simbir_go
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
    volumes: 
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80" 
    entrypoint: 
      - uvicorn
      - simbir_go.entrypoints.fastapi_app:app
      - --host=0.0.0.0
      - --port=80

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=simbir_go
      - POSTGRES_PASSWORD=sOm_e_dum8_p*ssw0|^d
    ports:
      - "54321:5432"
